import type { Chapter } from '../types';

const summaries: Record<string, { en: string; am: string }> = {
  intro: {
    en: "The introduction lays the groundwork for the entire Lean Startup methodology by contrasting traditional management practices with the needs of a modern startup. Eric Ries argues that startups operate under conditions of extreme uncertainty, and therefore require a different, more agile approach than established companies.\n\nThe core problem identified is that traditional business management, with its emphasis on long-term planning and rigid execution, is fundamentally unsuited for the volatile environment of a startup. This approach often leads to what Ries calls 'achieving failure'—successfully executing a plan that leads to a product nobody wants, thereby wasting time, money, and passion.\n\nThe solution proposed is a new discipline of entrepreneurial management. The fundamental goal of a startup is not to simply make money or even serve customers, but to learn how to build a sustainable business. This learning is rigorously managed through a process of continuous experimentation.\n\nThe cornerstone of this model is the Build-Measure-Learn feedback loop. It's a framework for turning ideas into products (Build), seeing how customers respond through data (Measure), and then deciding whether to change strategy (pivot) or continue on the current path (persevere) based on that learning (Learn). The primary objective is to minimize the total time through this loop, accelerating the learning process. As Ries emphasizes, the essential goal is to learn faster than the competition to win.",
    am: "መግቢያው፣ ባህላዊ የአስተዳደር ልምዶችን ከዘመናዊ ጅምር ንግድ ፍላጎቶች ጋር በማነፃፀር ለመላው የሊን ስታርታፕ ዘዴ መሰረት ይጥላል። ኤሪክ ሪስ እንደሚከራከረው፣ ጅምር ንግዶች በአስከፊ እርግጠኛ አለመሆን ሁኔታዎች ውስጥ ስለሚሰሩ፣ ከተመሰረቱ ኩባንያዎች የተለየ እና የበለጠ ቀልጣፋ አካሄድ ያስፈልጋቸዋል።\n\nዋናው ችግር ተብሎ የተለየው፣ በረጅም ጊዜ እቅድ እና ጥብቅ አፈፃፀም ላይ የሚያተኩረው ባህላዊ የንግድ አስተዳደር፣ ለጅምር ንግዶች ተለዋዋጭ አካባቢ በፍጹም ተስማሚ አለመሆኑ ነው። ይህ አካሄድ ብዙውን ጊዜ ሪስ 'ውድቀትን ማሳካት' ብሎ ወደሚጠራው ይመራል—ማንም የማይፈልገውን ምርት ወደሚያስገኝ እቅድ በተሳካ ሁኔታ መፈጸም፤ በዚህም ጊዜን፣ ገንዘብን እና ስሜትን ማባከን።\n\nየቀረበው መፍትሄ አዲስ የስራ ፈጠራ አስተዳደር ዘርፍ ነው። የጅምር ንግድ መሰረታዊ ግብ በቀላሉ ገንዘብ ማግኘት ወይም ደንበኞችን ማገልገል ሳይሆን፣ ዘላቂ ንግድ እንዴት መገንባት እንደሚቻል መማር ነው። ይህ ትምህርት በተከታታይ ሙከራ ሂደት በጥብቅ ይተዳደራል።\n\nየዚህ ሞዴል መሰረት 'ገንባ-ለካ-ተማር' (Build-Measure-Learn) የተባለው ግብረመልስ ዑደት ነው። ይህ ዑደት ሃሳቦችን ወደ ምርቶች ለመቀየር (መገንባት)፣ ደንበኞች በመረጃ እንዴት ምላሽ እንደሚሰጡ ለማየት (መለካት)፣ እና ከዚያም በዚያ ትምህርት ላይ በመመስረት ስልት መቀየር (መዞር) ወይም አሁን ባለው መንገድ መቀጠል (መጽናት) እንዳለበት ለመወሰን የሚያስችል ማዕቀፍ ነው። ዋናው አላማ በዚህ ዑደት ውስጥ የሚያልፈውን አጠቃላይ ጊዜ መቀነስ እና የመማር ሂደቱን ማፋጠን ነው። ሪስ እንደሚያስገነዝበው፣ ዋናው ግብ ለማሸነፍ ከተወዳዳሪዎች በበለጠ ፍጥነት መማር ነው።"
  },
  ch1: {
    en: "Chapter 1, 'Start,' redefines what a 'startup' is. It's not just two people in a garage; Ries defines a startup as 'a human institution designed to create a new product or service under conditions of extreme uncertainty.' This definition is intentionally broad, applying to new ventures within large corporations (intrapreneurs), non-profits, and government bodies, not just new companies.\n\nThe key insight is that entrepreneurship itself is a form of management. It is not chaos or a 'just do it' attitude. Rather, it requires a new kind of management specifically geared to its context of extreme uncertainty. The goal isn't just to produce a product, but to systematically de-risk the business idea and discover a path to a sustainable business model before the initial funding runs out.",
    am: "ምዕራፍ 1, 'መጀመር,' 'ጅምር ንግድ' ምን እንደሆነ እንደገና ይተነትናል። እሱ በጋራዥ ውስጥ ያሉ ሁለት ሰዎች ብቻ አይደለም፤ ሪስ ጅምር ንግድን 'በአስከፊ እርግጠኛ አለመሆን ሁኔታዎች ውስጥ አዲስ ምርት ወይም አገልግሎት ለመፍጠር የተነደፈ የሰው ተቋም' በማለት ይገልጸዋል። ይህ ትርጓሜ ሆን ተብሎ ሰፊ ሲሆን፣ ለአዳዲስ ኩባንያዎች ብቻ ሳይሆን በትልልቅ ኮርፖሬሽኖች ውስጥ ላሉ አዳዲስ ሥራዎች (intrapreneurs)፣ ለትርፍ ላልሆኑ ድርጅቶች እና ለመንግስት አካላትም ይሠራል።\n\nቁልፍ ግንዛቤው ስራ ፈጣሪነት ራሱ የአስተዳደር አይነት መሆኑ ነው። እሱ ሁከት ወይም 'ዝም ብለህ ስራው' የሚል አስተሳሰብ አይደለም። ይልቁንም፣ በተለይ ለአስከፊ እርግጠኛ አለመሆን ሁኔታ የተዘጋጀ አዲስ አይነት አስተዳደር ይጠይቃል። ግቡ ምርት ማምረት ብቻ ሳይሆን፣ የንግድ ሃሳቡን ስጋቶች በስርዓት መቀነስ እና የመጀመሪያው የገንዘብ ድጋፍ ከማለቁ በፊት ወደ ዘላቂ የንግድ ሞዴል የሚወስድ መንገድ ማግኘት ነው።"
  },
  ch2: {
    en: "Chapter 2, 'Define,' introduces the core metric of progress for a Lean Startup: 'validated learning.' Traditional metrics like revenue, profit, or lines of code written can be misleading 'vanity metrics' in the early stages. A startup can have zero revenue but be learning immense amounts about what customers want.\n\nValidated learning is the rigorous, empirical, and data-driven process of demonstrating that the team has discovered valuable truths about the startup's present and future business prospects. It is the real learning that comes from running experiments. For example, learning that customers are willing to pay for a specific feature is validated learning; simply building the feature is not. This concept forces founders to confront the truth about their vision and shifts the focus from 'Can we build this product?' to 'Should we build this product?' and 'Can we build a sustainable business around this set of products and services?'",
    am: "ምዕራፍ 2, 'መወሰን,' ለሊን ስታርታፕ ዋናውን የእድገት መለኪያ ያስተዋውቃል፥ ይኸውም 'የተረጋገጠ ትምህርት' (validated learning) ነው። እንደ ገቢ፣ ትርፍ ወይም የተጻፉ የኮድ መስመሮች ያሉ ባህላዊ መለኪያዎች በመጀመሪያዎቹ ደረጃዎች ላይ አሳሳች 'ከንቱ መለኪያዎች' ሊሆኑ ይችላሉ። አንድ ጅምር ንግድ ምንም ገቢ ላይኖረው ይችላል፤ ነገር ግን ደንበኞች ምን እንደሚፈልጉ ከፍተኛ መጠን ያለው ትምህርት እያገኘ ሊሆን ይችላል።\n\nየተረጋገጠ ትምህርት፣ ቡድኑ ስለ ጅምር ንግዱ የአሁኑ እና የወደፊት የንግድ ተስፋዎች ጠቃሚ እውነቶችን እንዳገኘ የሚያሳይ ጥብቅ፣ ተጨባጭ እና በመረጃ ላይ የተመሰረተ ሂደት ነው። ይህም ሙከራዎችን ከማካሄድ የሚመጣ እውነተኛ ትምህርት ነው። ለምሳሌ፣ ደንበኞች ለአንድ የተወሰነ ባህሪ ለመክፈል ፈቃደኛ መሆናቸውን መማር የተረጋገጠ ትምህርት ነው፤ ባህሪውን ዝም ብሎ መገንባት ግን አይደለም። ይህ ጽንሰ-ሀሳብ መስራቾች ስለ ራዕያቸው እውነቱን እንዲጋፈጡ ያስገድዳቸዋል እናም ትኩረቱን ከ'ይህን ምርት መገንባት እንችላለን?' ወደ 'ይህን ምርት መገንባት አለብን?' እና 'በዚህ የምርቶች እና አገልግሎቶች ስብስብ ዙሪያ ዘላቂ ንግድ መገንባት እንችላለን?' ወደሚለው ይለውጣል።"
  },
  ch3: {
    en: "Chapter 3, 'Learn,' dives deeper into the critical difference between 'vanity metrics' and 'actionable metrics.' Vanity metrics are numbers that look good on the surface (e.g., total sign-ups, cumulative downloads) but often hide the underlying truth and don't help in making clear decisions.\n\nActionable metrics, in contrast, demonstrate clear cause and effect, tying specific actions to observable outcomes. They are the foundation of validated learning. The book champions three key tools for generating actionable metrics:\n1.  **Cohort Analysis:** Instead of looking at cumulative totals, this tracks the behavior of groups of customers (cohorts) over time. This can reveal if product changes are actually improving customer behavior (like retention or engagement) for new users compared to old ones.\n2.  **Split Testing (A/B Testing):** This involves showing different versions of a product to different groups of users at the same time to see which version performs better against a specific goal. It provides clear, scientific proof of what works.\n3.  **A Clear Standard:** Metrics are meaningless without a clear understanding of what success looks like. Actionable metrics must be tied to the specific, falsifiable hypotheses the team is trying to test.",
    am: "ምዕራፍ 3, 'መማር,' 'በከንቱ መለኪያዎች' እና 'በተግባራዊ መለኪያዎች' መካከል ያለውን ወሳኝ ልዩነት በጥልቀት ይዳስሳል። ከንቱ መለኪያዎች ላዩን ሲታዩ ጥሩ የሚመስሉ ቁጥሮች ናቸው (ለምሳሌ፣ አጠቃላይ ምዝገባዎች፣ ድምር ውርዶች)፤ ነገር ግን ብዙውን ጊዜ ስር የሰደደውን እውነት ይደብቃሉ እና ግልጽ ውሳኔዎችን ለማድረግ አያግዙም።\n\nበተቃራኒው፣ ተግባራዊ መለኪያዎች ግልጽ የሆነ ምክንያት እና ውጤት ያሳያሉ፤ የተወሰኑ እርምጃዎችን ከሚታዩ ውጤቶች ጋር ያገናኛሉ። እነሱ የተረጋገጠ ትምህርት መሰረት ናቸው። መጽሐፉ ተግባራዊ መለኪያዎችን ለማመንጨት ሶስት ቁልፍ መሳሪያዎችን ይደግፋል፥\n1.  **የቡድን ትንተና (Cohort Analysis):** ድምር ውጤቶችን ከመመልከት ይልቅ፣ ይህ የደንበኛ ቡድኖችን (cohorts) ባህሪ በጊዜ ሂደት ይከታተላል። ይህ የምርት ለውጦች ለአዲስ ተጠቃሚዎች ከድሮዎቹ ጋር ሲነፃፀር የደንበኞችን ባህሪ (እንደ ጥበቃ ወይም ተሳትፎ) በእርግጥ እያሻሻሉ መሆናቸውን ሊገልጥ ይችላል።\n2.  **ሁለትዮሽ ሙከራ (Split Testing / A/B Testing):** ይህ የትኛው ስሪት ከተወሰነ ግብ አንፃር በተሻለ ሁኔታ እንደሚሰራ ለማየት የተለያዩ የምርት ስሪቶችን ለተለያዩ የተጠቃሚ ቡድኖች በተመሳሳይ ጊዜ ማሳየትን ያካትታል። ምን እንደሚሰራ ግልጽ እና ሳይንሳዊ ማስረጃ ይሰጣል።\n3.  **ግልጽ መስፈርት:** ስኬት ምን እንደሚመስል ግልጽ ግንዛቤ ከሌለ መለኪያዎች ትርጉም የላቸውም። ተግባራዊ መለኪያዎች ቡድኑ ሊፈትናቸው ከሚሞክራቸው የተወሰኑ እና ሊካዱ ከሚችሉ መላምቶች ጋር መያያዝ አለባቸው።"
  },
  ch4: {
    en: "Chapter 4, 'Experiment,' solidifies the idea that a startup's entire journey should be viewed as a series of experiments. Every product feature, marketing campaign, or business strategy is not a fact, but a hypothesis that needs to be tested.\n\nThe scientific method is directly applied to the startup world: formulate a hypothesis, predict the outcome, and then design an experiment to test it. For example, a hypothesis might be: 'We believe adding a one-click sign-up via Google will increase new user conversion by 20%.' The experiment is to build that feature (the 'Build' part of the loop) and then measure the result using a split test (the 'Measure' part). The analysis of this result constitutes the 'Learn' part.\n\nThis approach transforms debates based on opinions ('I think users want this feature!') into evidence-based decisions. By treating everything as an experiment, the startup continuously gathers validated learning and systematically navigates the uncertainty it faces, making informed decisions on its path to a sustainable business.",
    am: "ምዕራፍ 4, 'መሞከር,' የጅምር ንግድ መላው ጉዞ እንደ ተከታታይ ሙከራዎች መታየት አለበት የሚለውን ሀሳብ ያጠናክራል። እያንዳንዱ የምርት ባህሪ፣ የግብይት ዘመቻ ወይም የንግድ ስልት እውነታ ሳይሆን፣ መፈተሽ ያለበት መላምት ነው።\n\nሳይንሳዊ ዘዴው በቀጥታ በጅምር ንግድ አለም ላይ ይተገበራል፥ መላምት ማዘጋጀት፣ ውጤቱን መተንበይ፣ እና ከዚያም እሱን ለመፈተሽ ሙከራ መንደፍ። ለምሳሌ፣ አንድ መላምት እንዲህ ሊሆን ይችላል፥ 'በጎግል በኩል በአንድ ጠቅታ መመዝገብን መጨመር የአዲስ ተጠቃሚ ልወጣን በ20% ይጨምራል ብለን እናምናለን።' ሙከራው ያንን ባህሪ መገንባት (የዑደቱ 'ገንባ' ክፍል) እና ከዚያም ውጤቱን በሁለትዮሽ ሙከራ በመጠቀም መለካት (የ'ለካ' ክፍል) ነው። የዚህ ውጤት ትንተና የ'ተማር' ክፍልን ይመሰርታል።\n\nይህ አካሄድ በሀሳብ ላይ የተመሰረቱ ክርክሮችን ('ተጠቃሚዎች ይህን ባህሪ ይፈልጋሉ ብዬ አስባለሁ!') ወደ ማስረጃ ላይ የተመሰረቱ ውሳኔዎች ይለውጣል። ሁሉንም ነገር እንደ ሙከራ በመቁጠር፣ ጅምር ንግዱ በተከታታይ የተረጋገጠ ትምህርት ይሰበስባል እና የሚገጥመውን እርግጠኛ አለመሆን በስርዓት ይዳስሳል፤ ይህም ወደ ዘላቂ ንግድ በሚወስደው መንገድ ላይ በመረጃ የተደገፉ ውሳኔዎችን እንዲያደርግ ያስችለዋል።"
  },
  ch5: {
    en: "Chapter 5, 'Leap,' focuses on identifying and testing the riskiest assumptions in any business plan, which Ries calls 'leap-of-faith assumptions.' Before investing significant time and resources, a startup must test these foundational beliefs. There are two primary leap-of-faith assumptions:\n\n1.  **The Value Hypothesis:** This tests whether a product or service truly delivers value to customers once they are using it. Will customers actually use the product? Is it solving a real problem or fulfilling a real need for them? A crucial quote is, 'If we build it, will they come?' is less important than 'If they come, will they stay?'\n\n2.  **The Growth Hypothesis:** This tests how new customers will discover a product or service. How will the startup reach its target audience and grow its customer base? Will it be through word-of-mouth, paid advertising, or as a side effect of normal use?\n\nThe entire Lean Startup process is designed to test these two hypotheses as quickly and cheaply as possible. Proving them wrong early on isn't failure; it's learning that saves the company from building something that provides no value or has no path to growth.",
    am: "ምዕራፍ 5, 'ዝላይ,' በማንኛውም የንግድ እቅድ ውስጥ በጣም አደገኛ የሆኑትን ግምቶች በመለየት እና በመፈተን ላይ ያተኩራል፤ ሪስ እነዚህን 'የእምነት ዝላይ ግምቶች' (leap-of-faith assumptions) ብሎ ይጠራቸዋል። አንድ ጅምር ንግድ ከፍተኛ ጊዜ እና ሀብቶችን ከማፍሰሱ በፊት፣ እነዚህን መሰረታዊ እምነቶች መፈተሽ አለበት። ሁለት ዋና ዋና የእምነት ዝላይ ግምቶች አሉ፥\n\n1.  **የዋጋ መላምት (Value Hypothesis):** ይህ አንድ ምርት ወይም አገልግሎት ደንበኞች ከተጠቀሙበት በኋላ በእርግጥ ዋጋ እንደሚሰጣቸው ይፈትናል። ደንበኞች ምርቱን በእርግጥ ይጠቀሙታል? ለእነሱ እውነተኛ ችግር እየፈታ ነው ወይስ እውነተኛ ፍላጎትን እያሟላ ነው? አንድ ወሳኝ ጥቅስ፣ 'ከገነባነው ይመጣሉ?' ከሚለው ይልቅ 'ከመጡ ይቆያሉ?' የሚለው የበለጠ አስፈላጊ ነው።\n\n2.  **የእድገት መላምት (Growth Hypothesis):** ይህ አዲስ ደንበኞች አንድን ምርት ወይም አገልግሎት እንዴት እንደሚያገኙ ይፈትናል። ጅምር ንግዱ ዒላማ ታዳሚዎቹን እንዴት ይደርሳል እና የደንበኞቹን መሰረት ያሳድጋል? በአፍ ቃል፣ በሚከፈልበት ማስታወቂያ፣ ወይስ በተለመደው አጠቃቀም የጎንዮሽ ውጤት?\n\nመላው የሊን ስታርታፕ ሂደት እነዚህን ሁለት መላምቶች በተቻለ ፍጥነት እና በርካሽ ዋጋ ለመፈተሽ የተነደፈ ነው። ገና ከጅምሩ ስህተት መሆናቸውን ማረጋገጥ ውድቀት አይደለም፤ እሱ ኩባንያውን ምንም ዋጋ የማይሰጥ ወይም የእድገት መንገድ የሌለውን ነገር ከመገንባት የሚያድን ትምህርት ነው።"
  },
  ch6: {
    en: "Chapter 6, 'Test,' introduces one of the most famous concepts from the book: the Minimum Viable Product (MVP). An MVP is not the smallest product imaginable or a buggy prototype. Ries defines it as 'that version of a new product which allows a team to collect the maximum amount of validated learning about customers with the least effort.'\n\nThe primary purpose of an MVP is to test the fundamental business hypotheses (the leap-of-faith assumptions), not to build a scalable product. It's an experiment. The chapter details several clever ways to build an MVP without writing extensive code:\n\n*   **Video MVP:** Dropbox famously started with a simple video demonstrating the intended functionality. The overwhelming response validated their value hypothesis before the product was even built.\n*   **Concierge MVP:** This involves manually providing the service for the first few customers to gauge their interest and learn about their needs. It prioritizes learning over efficiency.\n*   **Wizard of Oz MVP:** This looks like a fully automated service from the outside, but behind the scenes, humans are manually performing all the tasks. This tests the user experience and demand before building a complex back-end.",
    am: "ምዕራፍ 6, 'መፈተን,' ከመጽሐፉ ውስጥ በጣም ታዋቂ ከሆኑ ጽንሰ-ሀሳቦች አንዱን ያስተዋውቃል፥ አነስተኛው አዋጭ ምርት (MVP)። MVP ሊታሰብ የሚችል በጣም ትንሹ ምርት ወይም ስህተት የበዛበት ምሳሌ አይደለም። ሪስ 'አንድ ቡድን በትንሹ ጥረት ስለ ደንበኞች ከፍተኛውን የተረጋገጠ ትምህርት እንዲሰበስብ የሚያስችለው የአዲስ ምርት ስሪት' በማለት ይገልጸዋል።\n\nየMVP ዋና ዓላማ መሰረታዊ የንግድ መላምቶችን (የእምነት ዝላይ ግምቶችን) መፈተሽ ነው፤ ሊሰፋ የሚችል ምርት መገንባት አይደለም። እሱ ሙከራ ነው። ምዕራፉ ሰፊ ኮድ ሳይጽፉ MVP ለመገንባት የሚያስችሉ በርካታ ብልሃታዊ መንገዶችን በዝርዝር ያብራራል፥\n\n*   **ቪዲዮ MVP:** ድሮፕቦክስ በታዋቂነት የጀመረው የታሰበውን ተግባር የሚያሳይ ቀላል ቪዲዮ በማሳየት ነበር። ከፍተኛው ምላሽ ምርቱ ከመገንባቱ በፊት የዋጋ መላምታቸውን አረጋግጧል።\n*   **ኮንሲየርጅ MVP:** ይህ ፍላጎታቸውን ለመለካት እና ስለ ፍላጎቶቻቸው ለመማር ለመጀመሪያዎቹ ጥቂት ደንበኞች አገልግሎቱን በእጅ መስጠትን ያካትታል። ከውጤታማነት ይልቅ ለመማር ቅድሚያ ይሰጣል።\n*   **የኦዝ ጠንቋይ MVP:** ይህ ከውጭ ሲታይ ሙሉ በሙሉ በራስ-ሰር የሚሰራ አገልግሎት ይመስላል፤ ነገር ግን ከትዕይንቱ በስተጀርባ፣ ሰዎች ሁሉንም ተግባራት በእጅ እያከናወኑ ነው። ይህ ውስብስብ የጀርባ ስርዓት ከመገንባቱ በፊት የተጠቃሚውን ልምድ እና ፍላጎት ይፈትናል።"
  },
  ch7: {
    en: "Chapter 7, 'Measure,' introduces a framework for accountability called 'innovation accounting.' This is a necessary alternative to traditional accounting, which is ineffective for early-stage startups that may have no revenue or profit to measure. Innovation accounting provides a way to see if a startup is actually making progress toward building a sustainable business.\n\nIt works in three distinct steps:\n1.  **Establish the Baseline:** Use an MVP to get real, quantitative data on where the business stands right now. This includes metrics like conversion rates, sign-up rates, and customer lifetime value. This baseline is the starting point.\n2.  **Tune the Engine:** The startup then systematically makes changes and improvements to the product. Each change is an experiment designed to improve one of the key metrics from the baseline, moving them closer to the ideal state required for a sustainable business.\n3.  **Pivot or Persevere:** After a set of experiments and tuning efforts, the team must face a critical decision. If the metrics are improving and moving toward the goal, they should persevere. If the experiments are not producing significant progress despite multiple efforts, it is a sign that the current strategy is flawed and a pivot is required. Innovation accounting makes this decision data-driven, not emotional.",
    am: "ምዕራፍ 7, 'መለካት,' 'የፈጠራ ሂሳብ አያያዝ' (innovation accounting) የሚባል የተጠያቂነት ማዕቀፍ ያስተዋውቃል። ይህ ለባህላዊ የሂሳብ አያያዝ አስፈላጊ አማራጭ ነው፤ ምክንያቱም ባህላዊው ዘዴ ገቢ ወይም ትርፍ ለሌላቸው የመጀመሪያ ደረጃ ጅምር ንግዶች ውጤታማ አይደለም። የፈጠራ ሂሳብ አያያዝ አንድ ጅምር ንግድ ዘላቂ ንግድ ለመገንባት በእርግጥ እድገት እያደረገ መሆኑን ለማየት የሚያስችል መንገድ ይሰጣል።\n\nበሶስት የተለያዩ ደረጃዎች ይሰራል፥\n1.  **መሰረታዊ መስመርን ማቋቋም:** ንግዱ አሁን የት ላይ እንደሚገኝ እውነተኛ እና መጠናዊ መረጃ ለማግኘት MVPን መጠቀም። ይህ እንደ የልወጣ ምጣኔዎች፣ የምዝገባ ምጣኔዎች እና የደንበኛ የህይወት ዘመን ዋጋ ያሉ መለኪያዎችን ያካትታል። ይህ መሰረታዊ መስመር መነሻ ነጥብ ነው።\n2.  **ሞተሩን ማስተካከል:** ከዚያም ጅምር ንግዱ በስርዓት በምርቱ ላይ ለውጦችን እና ማሻሻያዎችን ያደርጋል። እያንዳንዱ ለውጥ ከመሰረታዊ መስመሩ ውስጥ አንዱን ቁልፍ መለኪያ ለማሻሻል የተነደፈ ሙከራ ሲሆን፣ ለዘላቂ ንግድ ወደሚያስፈልገው ተስማሚ ሁኔታ ያቀርባቸዋል።\n3.  **መዞር ወይም መጽናት:** ከተወሰኑ ሙከራዎች እና የማስተካከያ ጥረቶች በኋላ፣ ቡድኑ ወሳኝ ውሳኔ መጋፈጥ አለበት። መለኪያዎቹ እየተሻሻሉ እና ወደ ግቡ እየተጓዙ ከሆነ፣ መጽናት አለባቸው። ሙከራዎቹ ከበርካታ ጥረቶች በኋላ ጉልህ እድገት የማያሳዩ ከሆነ፣ ይህ የአሁኑ ስልት የተሳሳተ መሆኑን እና መዞር እንደሚያስፈልግ ምልክት ነው። የፈጠራ ሂሳብ አያያዝ ይህን ውሳኔ በስሜት ላይ ሳይሆን በመረጃ ላይ የተመሰረተ ያደርገዋል።"
  },
  ch8: {
    en: "Chapter 8, 'Pivot (or Persevere),' addresses the most critical strategic decision a startup must make. A 'pivot' is not an admission of failure. Ries defines it as a 'structured course correction designed to test a new fundamental hypothesis about the product, business model, and engine of growth.' It's a change in strategy, not a change in vision.\n\nThe runway of a startup should be measured not by time, but by the number of pivots it can still make before running out of money. The chapter catalogs several common types of pivots:\n\n*   **Zoom-in Pivot:** A single feature of a product becomes the entire product.\n*   **Zoom-out Pivot:** What was considered the whole product becomes a single feature of a much larger product.\n*   **Customer Segment Pivot:** The product solves a real problem, but for a different customer segment than originally anticipated.\n*   **Platform Pivot:** A change from being an application to a platform that others can build on, or vice-versa.\n*   **Engine of Growth Pivot:** Switching the company's growth strategy (e.g., from a viral to a paid growth model).\n\nRegular 'pivot or persevere' meetings, grounded in the data from innovation accounting, are essential for making these tough decisions effectively.",
    am: "ምዕራፍ 8, 'መዞር (ወይም መጽናት),' አንድ ጅምር ንግድ ሊወስነው የሚገባውን በጣም ወሳኝ ስልታዊ ውሳኔ ይመለከታል። 'መዞር' (pivot) የውድቀት ማረጋገጫ አይደለም። ሪስ 'ስለ ምርቱ፣ የንግድ ሞዴሉ እና የእድገት ሞተሩ አዲስ መሰረታዊ መላምትን ለመፈተሽ የተነደፈ የተዋቀረ የእርምት እርምጃ' በማለት ይገልጸዋል። እሱ በራዕይ ላይ ሳይሆን በስልት ላይ የሚደረግ ለውጥ ነው።\n\nየአንድ ጅምር ንግድ የህይወት ዘመን በጊዜ መለካት የለበትም፤ ይልቁንም ገንዘቡ ከማለቁ በፊት ሊያደርጋቸው በሚችላቸው የመዞሪያዎች ብዛት ነው። ምዕራፉ በርካታ የተለመዱ የመዞሪያ ዓይነቶችን ይዘረዝራል፥\n\n*   **ማጉላት መዞር (Zoom-in Pivot):** የአንድ ምርት አንድ ባህሪ ሙሉ ምርት ይሆናል።\n*   **ማሳነስ መዞር (Zoom-out Pivot):** ሙሉ ምርት ተብሎ ይታሰብ የነበረው ነገር የትልቅ ምርት አንድ ባህሪ ይሆናል።\n*   **የደንበኛ ክፍል መዞር (Customer Segment Pivot):** ምርቱ እውነተኛ ችግር ይፈታል፤ ነገር ግን መጀመሪያ ከታሰበው የተለየ የደንበኛ ክፍል ላለ።\n*   **የፕላትፎርም መዞር (Platform Pivot):** ከአፕሊኬሽን ወደ ሌሎች ሊገነቡበት የሚችሉት ፕላትፎርም ወይም በተቃራኒው መቀየር።\n*   **የእድገት ሞተር መዞር (Engine of Growth Pivot):** የኩባንያውን የእድገት ስልት መቀየር (ለምሳሌ፣ ከተላላፊ ወደሚከፈልበት የእድገት ሞዴል)።\n\nበፈጠራ ሂሳብ አያያዝ መረጃ ላይ የተመሰረቱ መደበኛ 'መዞር ወይም መጽናት' ስብሰባዎች፣ እነዚህን ከባድ ውሳኔዎች በብቃት ለመወሰን አስፈላጊ ናቸው።"
  },
  ch9: {
    en: "Chapter 9, 'Batch,' borrows a core concept from lean manufacturing: the power of working in small batches. The counterintuitive insight is that producing one unit at a time (or in very small batches) is faster and more efficient than producing a large batch all at once.\n\nIn software development, a 'large batch' is equivalent to developing many features over several months before a single release. This approach is risky because it delays feedback, hides defects until the very end, and increases the complexity of debugging. If the entire batch is based on a flawed assumption, all the work is wasted.\n\nWorking in small batches, best exemplified by the practice of 'Continuous Deployment' (releasing new code to customers multiple times a day), has profound benefits. It allows the team to:\n*   Get feedback much faster, shortening the Build-Measure-Learn loop.\n*   Identify and fix bugs immediately, as each change is small and isolated.\n*   Reduce the risk of catastrophic failure.\n*   Increase developer productivity and morale by seeing their work go live quickly.\n\nThe underlying principle is to accelerate feedback and learning by reducing the cycle time of development.",
    am: "ምዕራፍ 9, 'ቡድን,' ከሊን ማኑፋክቸሪንግ አንድ ዋና ጽንሰ-ሀሳብ ይዋሳል፥ በትንንሽ ቡድኖች የመስራት ኃይል። ያልተለመደው ግንዛቤ በአንድ ጊዜ አንድ ክፍል ማምረት (ወይም በጣም በትንንሽ ቡድኖች) በአንድ ጊዜ ትልቅ ቡድን ከማምረት የበለጠ ፈጣን እና ቀልጣፋ መሆኑ ነው።\n\nበሶፍትዌር ልማት ውስጥ፣ 'ትልቅ ቡድን' ማለት አንድ ጊዜ ከመለቀቁ በፊት ለብዙ ወራት በርካታ ባህሪያትን ማልማት ማለት ነው። ይህ አካሄድ አደገኛ ነው፤ ምክንያቱም ግብረመልስን ያዘገያል፣ ጉድለቶችን እስከ መጨረሻው ይደብቃል፣ እና የስህተት ፍለጋን ውስብስብነት ይጨምራል። መላው ቡድን በተሳሳተ ግምት ላይ የተመሰረተ ከሆነ፣ ሁሉም ስራ ይባክናል።\n\nበ'ቀጣይነት ያለው ማሰማራት' (በቀን ውስጥ ብዙ ጊዜ አዲስ ኮድ ለደንበኞች መልቀቅ) ልምድ እንደሚታየው በትንንሽ ቡድኖች መስራት ጥልቅ ጥቅሞች አሉት። ይህም ቡድኑ የሚከተሉትን እንዲያደርግ ያስችለዋል፥\n*   ግብረመልስን በጣም በፍጥነት ማግኘት፤ ይህም የ'ገንባ-ለካ-ተማር' ዑደትን ያሳጥራል።\n*   እያንዳንዱ ለውጥ ትንሽ እና የተለየ ስለሆነ ስህተቶችን ወዲያውኑ መለየት እና ማስተካከል።\n*   የከፍተኛ ውድቀት ስጋትን መቀነስ።\n*   ስራቸው በፍጥነት በቀጥታ ሲተላለፍ በማየት የገንቢዎችን ምርታማነት እና ስሜት መጨመር።\n\nስር የሰደደው መርህ የልማት ዑደት ጊዜን በመቀነስ ግብረመልስን እና ትምህርትን ማፋጠን ነው።"
  },
  ch10: {
    en: "Chapter 10, 'Grow,' focuses on the mechanics of sustainable growth. Ries argues that sustainable growth comes from the actions of past customers, and he identifies three primary 'engines of growth.' A startup must focus its efforts on one engine at a time.\n\n1.  **The Sticky Engine:** This engine is all about user retention. The goal is to make the product so engaging and valuable that customers 'stick' around. Growth happens when the rate of new customer acquisition is greater than the churn rate (the rate at which customers leave). The key metric to watch is churn.\n\n2.  **The Viral Engine:** Growth here is a direct consequence of customers using the product. Each user brings in one or more new users, creating exponential growth. The key metric is the 'viral coefficient'—the number of new customers an existing customer generates. If this coefficient is greater than 1, the product will have viral growth.\n\n3.  **The Paid Engine:** This engine involves paying to acquire customers, through methods like advertising or sales teams. For this engine to be sustainable, the Cost Per Acquisition (CPA) must be less than the Lifetime Value (LTV) of a customer. The company must be able to extract more value from a customer than it costs to acquire them.",
    am: "ምዕራፍ 10, 'ማደግ,' በዘላቂ እድገት ስልቶች ላይ ያተኩራል። ሪስ እንደሚከራከረው፣ ዘላቂ እድገት የሚመጣው ካለፉት ደንበኞች ድርጊቶች ሲሆን፣ ሶስት ዋና 'የእድገት ሞተሮችን' ይለያል። አንድ ጅምር ንግድ ጥረቱን በአንድ ጊዜ በአንድ ሞተር ላይ ማተኮር አለበት።\n\n1.  **ተለጣፊው ሞተር (Sticky Engine):** ይህ ሞተር ሙሉ በሙሉ ስለ ተጠቃሚ ጥበቃ ነው። ግቡ ምርቱን በጣም አሳታፊ እና ዋጋ ያለው በማድረግ ደንበኞች 'እንዲጣበቁ' ማድረግ ነው። እድገት የሚከሰተው የአዲስ ደንበኛ ማግኛ ምጣኔ ከመልቀቂያ ምጣኔ (ደንበኞች የሚለቁበት ምጣኔ) ሲበልጥ ነው። ለመከታተል ቁልፍ መለኪያው የመልቀቂያ ምጣኔ (churn) ነው።\n\n2.  **ተላላፊው ሞተር (Viral Engine):** እዚህ ላይ እድገት ደንበኞች ምርቱን ከመጠቀማቸው የሚመጣ ቀጥተኛ ውጤት ነው። እያንዳንዱ ተጠቃሚ አንድ ወይም ከዚያ በላይ አዲስ ተጠቃሚዎችን ያመጣል፤ ይህም ገደብ የለሽ እድገት ይፈጥራል። ቁልፍ መለኪያው 'የተላላፊነት ቅንጅት' (viral coefficient) ነው—አንድ ነባር ደንበኛ የሚያመነጨው የአዲስ ደንበኞች ብዛት። ይህ ቅንጅት ከ1 በላይ ከሆነ፣ ምርቱ ተላላፊ እድገት ይኖረዋል።\n\n3.  **የሚከፈልበት ሞተር (Paid Engine):** ይህ ሞተር እንደ ማስታወቂያ ወይም የሽያጭ ቡድኖች ባሉ ዘዴዎች ደንበኞችን ለማግኘት መክፈልን ያካትታል። ይህ ሞተር ዘላቂ እንዲሆን፣ የማግኛ ወጪ (CPA) ከአንድ ደንበኛ የህይወት ዘመን ዋጋ (LTV) ያነሰ መሆን አለበት። ኩባንያው አንድን ደንበኛ ከማግኛ ወጪው የበለጠ ዋጋ ማውጣት መቻል አለበት።"
  },
  ch11: {
    en: "Chapter 11, 'Adapt,' addresses the challenge of building an organization that can scale without losing its innovative speed. As companies grow, bureaucracy can slow down the Build-Measure-Learn loop. The key is to build an 'adaptive organization.'\n\nA central technique for this is the 'Five Whys.' When a problem or failure occurs (e.g., a server crash), instead of just fixing the surface-level issue, the team asks 'Why?' five times to drill down to the root cause. This process helps shift the blame from individuals to systemic issues.\n\nFor example:\n1. Why did the server crash? - A new piece of code had a bug.\n2. Why did the bug get deployed? - The tests didn't catch it.\n3. Why didn't the tests catch it? - The developer who wrote the test was new and didn't know about this edge case.\n4. Why didn't he know? - He wasn't properly trained on the testing system.\n5. Why wasn't he trained? - His manager hasn't prioritized training for new engineers.\n\nThe root cause isn't a bad developer; it's a lack of a training process. The solution is to create a training program, which is an investment that prevents an entire class of future problems. This method allows the organization to learn and adapt from its mistakes.",
    am: "ምዕራፍ 11, 'መለማመድ,' የፈጠራ ፍጥነቱን ሳያጣ ሊሰፋ የሚችል ድርጅት የመገንባትን ፈተና ይመለከታል። ኩባንያዎች ሲያድጉ፣ ቢሮክራሲ የ'ገንባ-ለካ-ተማር' ዑደትን ሊያዘገይ ይችላል። ቁልፉ 'ተስማሚ ድርጅት' መገንባት ነው።\n\nለዚህ አንድ ማዕከላዊ ዘዴ 'አምስቱ ለምን' (Five Whys) ነው። አንድ ችግር ወይም ውድቀት ሲከሰት (ለምሳሌ፣ ሰርቨር ሲበላሽ)፣ ላዩን ያለውን ችግር ብቻ ከማስተካከል ይልቅ፣ ቡድኑ ወደ ስር መንስኤው ለመድረስ 'ለምን?' ብሎ አምስት ጊዜ ይጠይቃል። ይህ ሂደት ጥፋቱን ከግለሰቦች ወደ ስርአታዊ ጉዳዮች እንዲሸጋገር ይረዳል።\n\nለምሳሌ፥\n1. ሰርቨሩ ለምን ተበላሸ? - አዲስ የኮድ ክፍል ስህተት ነበረበት።\n2. ስህተቱ ለምን ተሰማራ? - ሙከራዎቹ አላገኙትም።\n3. ሙከራዎቹ ለምን አላገኙትም? - ሙከራውን የጻፈው ገንቢ አዲስ ስለነበር ይህን ልዩ ሁኔታ አያውቅም ነበር።\n4. ለምን አላወቀም? - በሙከራ ስርዓቱ ላይ በትክክል አልሰለጠነም።\n5. ለምን አልሰለጠነም? - ስራ አስኪያጁ ለአዲስ መሐንዲሶች ስልጠና ቅድሚያ አልሰጠም።\n\nስር መንስኤው መጥፎ ገንቢ አይደለም፤ የስልጠና ሂደት አለመኖር ነው። መፍትሄው ወደፊት የሚመጡ ተመሳሳይ ችግሮችን በሙሉ የሚከላከል የስልጠና ፕሮግራም መፍጠር ነው። ይህ ዘዴ ድርጅቱ ከስህተቶቹ እንዲማር እና እንዲላመድ ያስችለዋል።"
  },
  ch12: {
    en: "Chapter 12, 'Innovate,' tackles the question of how to apply Lean Startup principles within large, established companies. To survive long-term, all companies must be able to innovate. However, their existing processes and culture often crush new ideas.\n\nRies proposes creating a protected 'innovation sandbox' within the larger organization. This is a space where internal teams ('intrapreneurs') can operate with the speed and autonomy of a startup. For this to work, these teams need three things:\n\n1.  **A Scarce but Secure Budget:** The team has a dedicated budget that cannot be easily taken away, allowing them to run experiments without constant fear of losing funding.\n2.  **Autonomy to Develop and Test:** The team must have the authority to develop, market, and deploy its own products and experiments without going through layers of bureaucracy.\n3.  **A Personal Stake in the Outcome:** The innovators' career progression and compensation should be tied to the success of their venture, creating an incentive structure similar to that of external entrepreneurs. This allows large companies to create their own internal 'engines of discovery' to drive future growth.",
    am: "ምዕራፍ 12, 'መፍጠር,' በትልልቅ እና በተመሰረቱ ኩባንያዎች ውስጥ የሊን ስታርታፕ መርሆዎችን እንዴት መተግበር እንደሚቻል ጥያቄውን ይመለከታል። በረጅም ጊዜ ለመቆየት፣ ሁሉም ኩባንያዎች መፍጠር መቻል አለባቸው። ሆኖም፣ ነባር ሂደቶቻቸው እና ባህላቸው ብዙውን ጊዜ አዲስ ሀሳቦችን ያጠፋሉ።\n\nሪስ በትልቁ ድርጅት ውስጥ የተጠበቀ 'የፈጠራ ማጠሪያ ሳጥን' (innovation sandbox) መፍጠርን ሀሳብ ያቀርባል። ይህ የውስጥ ቡድኖች ('intrapreneurs') እንደ ጅምር ንግድ በፍጥነት እና በነጻነት ሊሰሩ የሚችሉበት ቦታ ነው። ይህ እንዲሰራ፣ እነዚህ ቡድኖች ሶስት ነገሮች ያስፈልጓቸዋል፥\n\n1.  **አነስተኛ ግን አስተማማኝ በጀት:** ቡድኑ በቀላሉ ሊወሰድ የማይችል የተወሰነ በጀት አለው፤ ይህም የገንዘብ ድጋፍ የማጣት ስጋት ሳይኖርባቸው ሙከራዎችን እንዲያካሂዱ ያስችላቸዋል።\n2.  **ለማልማት እና ለመፈተሽ ነጻነት:** ቡድኑ የራሱን ምርቶች እና ሙከራዎች ለማልማት፣ ለገበያ ለማቅረብ እና ለማሰማራት በበርካታ የቢሮክራሲ ደረጃዎች ሳያልፍ ስልጣን ሊኖረው ይገባል።\n3.  **በውጤቱ ላይ የግል ድርሻ:** የፈጣሪዎቹ የሙያ እድገት እና ክፍያ ከሥራቸው ስኬት ጋር መያያዝ አለበት፤ ይህም ከውጭ ስራ ፈጣሪዎች ጋር ተመሳሳይ የሆነ የማበረታቻ መዋቅር ይፈጥራል። ይህ ትልልቅ ኩባንያዎች የወደፊት እድገትን ለማምጣት የራሳቸውን የውስጥ 'የግኝት ሞተሮች' እንዲፈጥሩ ያስችላቸዋል።"
  },
  epilogue: {
    en: "The epilogue, 'Waste Not,' serves as a powerful conclusion, tying all the book's concepts together under a single, unifying theme: the elimination of waste. In the context of a startup, waste is not about inefficiency or shoddy work. The ultimate form of waste is 'building something that nobody wants.'\n\nEvery technique in the book—from validated learning and MVPs to pivots and small batches—is designed for one purpose: to minimize the total amount of time, money, and effort spent on ideas that don't lead to a sustainable business. By adopting a scientific and systematic approach, entrepreneurs can increase their chances of success by ensuring that their hard work is directed toward creating real value for real customers. The Lean Startup is, at its core, a methodology for sustainable innovation.",
    am: "የመጨረሻው ቃል, 'አታባክን,' የመጽሐፉን ጽንሰ-ሀሳቦች በሙሉ በአንድ ወጥ ጭብጥ ስር በማሰባሰብ እንደ ኃይለኛ መደምደሚያ ሆኖ ያገለግላል፥ የብክነትን ማስወገድ። በጅምር ንግድ አውድ ውስጥ፣ ብክነት ስለ ውጤታማነት ማነስ ወይም ጥራት የሌለው ስራ አይደለም። የመጨረሻው የብክነት አይነት 'ማንም የማይፈልገውን ነገር መገንባት' ነው።\n\nበመጽሐፉ ውስጥ ያለው እያንዳንዱ ዘዴ—ከተረጋገጠ ትምህርት እና ከMVPs ጀምሮ እስከ መዞር እና ትንንሽ ቡድኖች ድረስ—ለአንድ ዓላማ የተነደፈ ነው፥ ወደ ዘላቂ ንግድ የማይመሩ ሀሳቦች ላይ የሚፈሰውን አጠቃላይ ጊዜ፣ ገንዘብ እና ጥረት ለመቀነስ። ሳይንሳዊ እና ስልታዊ አካሄድን በመከተል፣ ስራ ፈጣሪዎች ጠንክሮ ስራቸው ለእውነተኛ ደንበኞች እውነተኛ ዋጋ ለመፍጠር መመራቱን በማረጋገጥ የስኬት እድላቸውን ከፍ ማድረግ ይችላሉ። ሊን ስታርታፕ፣ በመሰረቱ፣ ለዘላቂ ፈጠራ የተዘጋጀ ዘዴ ነው።"
  },
  join: {
    en: "The final section, 'Join the Movement,' is a call to action. Ries emphasizes that The Lean Startup is more than just a book or a collection of tactics; it's a global movement aimed at fundamentally changing how we think about innovation and management. He encourages everyone—entrepreneurs, managers in large companies, investors, and even government officials—to adopt these principles.\n\nThe message is one of shared learning and community. By applying these ideas, sharing the results (both successes and failures), and contributing to the collective knowledge base, we can make the process of innovation more capital-efficient, less wasteful, and ultimately more successful for everyone involved. It's an invitation to stop relying on myths and start applying a rigorous, scientific discipline to the art of creating the future.",
    am: "የመጨረሻው ክፍል, 'እንቅስቃሴውን ይቀላቀሉ,' የድርጊት ጥሪ ነው። ሪስ ሊን ስታርታፕ ከመጽሐፍ ወይም ከስልቶች ስብስብ በላይ መሆኑን አፅንዖት ይሰጣል፤ እሱ ስለ ፈጠራ እና አስተዳደር የምናስብበትን መንገድ በመሰረቱ ለመለወጥ ያለመ ዓለም አቀፍ እንቅስቃሴ ነው። ሁሉም ሰው—ስራ ፈጣሪዎች፣ በትልልቅ ኩባንያዎች ውስጥ ያሉ ስራ አስኪያጆች፣ ባለሀብቶች፣ እና እንዲያውም የመንግስት ባለስልጣናት—እነዚህን መርሆዎች እንዲቀበሉ ያበረታታል።\n\nመልዕክቱ የጋራ ትምህርት እና የማህበረሰብ ነው። እነዚህን ሀሳቦች በመተግበር፣ ውጤቶችን (ስኬቶችንም ሆነ ውድቀቶችን) በማካፈል፣ እና ለጋራ የእውቀት መሰረት አስተዋፅኦ በማድረግ፣ የፈጠራ ሂደቱን የበለጠ ካፒታል ቆጣቢ፣ ብክነት የሌለው፣ እና በመጨረሻም ለሁሉም ተሳታፊዎች የበለጠ ስኬታማ ማድረግ እንችላለን። እሱ በተረት ላይ መመካትን አቁመን የወደፊቱን የመፍጠር ጥበብ ላይ ጥብቅ እና ሳይንሳዊ ዘርፍን መተግበር እንድንጀምር የቀረበ ግብዣ ነው።"
  }
};

export const getChapterSummary = (chapterId: string, language: 'en' | 'am' = 'en'): string => {
  if (chapterId in summaries) {
    // The type assertion is safe because we check for existence first.
    const chapterSummaries = summaries[chapterId as keyof typeof summaries];
    return chapterSummaries[language];
  }
  return "Summary not found for this chapter.";
};
